#!/usr/bin/env bash
#
# Configure Jetson 40-pin header for the SPI screen (ILI9341 / ST7789).
#
# Required pin functions:
#   spi1  (19,21,23,24,26)  → /dev/spidev*.0  (MOSI/MISO/SCLK/CS0)
#   gpio  (13,16,18,22,37)  → spi3 group freed; pins 18 (RST) and 22 (DC) usable
#   gpio  (12,35,38,40)     → i2s2 group freed; pin 12 (LED backlight) usable
#
# A reboot is required after running this script.
#
# Usage:
#   ./scripts/configure_jetson_screen_pins.sh
#
set -eo pipefail

JETSON_IO="/opt/nvidia/jetson-io/jetson-io.py"
CFG_DIR="/etc/jetson-io"
CFG_FILE="$CFG_DIR/jetson-io.cfg"

echo "=== Jetson screen pin configuration ==="

# ── Preflight ─────────────────────────────────────────────────────
if [ ! -f "$JETSON_IO" ]; then
  echo "ERROR: $JETSON_IO not found — is this a Jetson?"
  exit 1
fi

# ── Check if already configured ───────────────────────────────────
echo ""
echo "--- Current SPI devices ---"
SPI_DEVS=$(ls /dev/spidev* 2>/dev/null || true)
if [ -n "$SPI_DEVS" ]; then
  echo "  Found: $SPI_DEVS"
  read -rp "  SPI already present. Re-apply config anyway? [y/N] " REPLY
  [[ "$REPLY" =~ ^[Yy]$ ]] || { echo "  Nothing to do."; exit 0; }
else
  echo "  None found — proceeding."
fi

# ── Write jetson-io config file ───────────────────────────────────
# jetson-io.py reads this file when --config is passed (JetPack 5+/6).
# Keys are the function-group names shown in the TUI; values are the
# selected function for that group's pins.
echo ""
echo "--- Writing $CFG_FILE ---"
sudo mkdir -p "$CFG_DIR"
sudo tee "$CFG_FILE" > /dev/null << 'EOF'
# HorseShitBot screen pin configuration
# Generated by configure_jetson_screen_pins.sh
[40pin Header]
spi1 = spi1
spi3 = gpio
i2s2 = gpio
EOF
echo "  Written."

# ── Apply via jetson-io ───────────────────────────────────────────
echo ""
echo "--- Applying config via jetson-io.py ---"

# Try --config flag (JetPack 5.1+ / 6.x non-interactive mode)
if sudo python3 "$JETSON_IO" --config "$CFG_FILE" 2>/dev/null; then
  echo "  Config applied successfully."
  APPLIED=1
else
  # Some builds use --no-ui flag instead
  if sudo python3 "$JETSON_IO" --no-ui --config "$CFG_FILE" 2>/dev/null; then
    echo "  Config applied successfully (--no-ui)."
    APPLIED=1
  else
    APPLIED=0
  fi
fi

# ── Fallback: manual instructions ────────────────────────────────
if [ "${APPLIED:-0}" = "0" ]; then
  echo ""
  echo "  Automatic config failed — complete these steps manually:"
  echo ""
  echo "  sudo python3 $JETSON_IO"
  echo ""
  echo "  Navigate to:  Configure Jetson 40pin Header"
  echo "                → Select desired functions for pins"
  echo ""
  echo "  Set the following rows (arrow keys to move, space to select):"
  echo ""
  echo "    spi1  (19,21,23,24,26)  →  [*] spi1"
  echo "    spi3  (13,16,18,22,37)  →  [*] gpio"
  echo "    i2s2  (12,35,38,40)     →  [*] gpio"
  echo ""
  echo "  Then: Save pin changes → Save and reboot"
  exit 0
fi

# ── Reboot prompt ─────────────────────────────────────────────────
echo ""
echo "=== Done — reboot required for overlay to take effect ==="
echo ""
read -rp "Reboot now? [y/N] " REPLY
if [[ "$REPLY" =~ ^[Yy]$ ]]; then
  sudo reboot
else
  echo "  Run 'sudo reboot' when ready."
  echo "  After reboot, verify with:  ls /dev/spidev*"
fi
