#!/usr/bin/env bash
#
# Configure Jetson 40-pin header for the SPI screen (ILI9341 / ST7789).
#
# Required pin functions:
#   spi1  (19,21,23,24,26)  → /dev/spidev*.0  (MOSI/MISO/SCLK/CS0)
#   gpio  (13,16,18,22,37)  → spi3 group freed; pins 18 (RST) and 22 (DC) usable
#   gpio  (12,35,38,40)     → i2s2 group freed; pin 12 (LED backlight) usable
#
# A reboot is required after running this script.
#
# Usage:
#   ./scripts/configure_jetson_screen_pins.sh
#
set -eo pipefail

JETSON_IO="/opt/nvidia/jetson-io/jetson-io.py"
CFG_DIR="/etc/jetson-io"
CFG_FILE="$CFG_DIR/jetson-io.cfg"

echo "=== Jetson screen pin configuration ==="

# ── Preflight ─────────────────────────────────────────────────────
if [ ! -f "$JETSON_IO" ]; then
  echo "ERROR: $JETSON_IO not found — is this a Jetson?"
  exit 1
fi

# ── Check current pin state ───────────────────────────────────────
echo ""
echo "--- Current pin state ---"
SPI_DEVS=$(ls /dev/spidev* 2>/dev/null || true)
if [ -n "$SPI_DEVS" ]; then
  echo "  SPI devices : $SPI_DEVS"
else
  echo "  SPI devices : none"
fi

# Check if spi3/i2s2 pins are already exported as GPIO
# Jetson GPIO sysfs: /sys/class/gpio/  — we probe by reading the pinmux state
PINMUX_BASE="/sys/kernel/debug/pinctrl"
if [ -d "$PINMUX_BASE" ]; then
  for PIN in 12 18 22; do
    STATE=$(grep -r "pin $PIN\b" "$PINMUX_BASE"/*/pinmux-pins 2>/dev/null | head -1 || true)
    echo "  Pin $PIN state : ${STATE:-unknown (run as root to read pinmux)}"
  done
fi

echo ""
echo "  Note: spidev present does NOT mean DC/RST/LED pins are muxed as GPIO."
echo "  Applying full config regardless..."

# ── Write jetson-io config file ───────────────────────────────────
# jetson-io.py reads this file when --config is passed (JetPack 5+/6).
# Keys are the function-group names shown in the TUI; values are the
# selected function for that group's pins.
echo ""
echo "--- Writing $CFG_FILE ---"
sudo mkdir -p "$CFG_DIR"
sudo tee "$CFG_FILE" > /dev/null << 'EOF'
# HorseShitBot screen pin configuration
# Generated by configure_jetson_screen_pins.sh
[40pin Header]
spi1 = spi1
spi3 = gpio
i2s2 = gpio
EOF
echo "  Written."

# ── Apply via jetson-io ───────────────────────────────────────────
echo ""
echo "--- Applying config via jetson-io.py ---"
echo "  jetson-io.py supports:"
sudo python3 "$JETSON_IO" --help 2>&1 | grep -E '^\s*--' | head -20 || true
echo ""

APPLIED=0

# Try --config flag (JetPack 5.1+ / 6.x non-interactive mode)
if sudo python3 "$JETSON_IO" --config "$CFG_FILE" 2>&1; then
  echo "  Config applied successfully."
  APPLIED=1
elif sudo python3 "$JETSON_IO" --no-ui --config "$CFG_FILE" 2>&1; then
  echo "  Config applied successfully (--no-ui)."
  APPLIED=1
fi

# ── Fallback: manual instructions ────────────────────────────────
if [ "${APPLIED:-0}" = "0" ]; then
  echo ""
  echo "  Automatic config failed — complete these steps manually:"
  echo ""
  echo "  sudo python3 $JETSON_IO"
  echo ""
  echo "  Navigate to:  Configure Jetson 40pin Header"
  echo "                → Select desired functions for pins"
  echo ""
  echo "  Set the following rows (arrow keys to move, space to select):"
  echo ""
  echo "    spi1  (19,21,23,24,26)  →  [*] spi1"
  echo "    spi3  (13,16,18,22,37)  →  [*] gpio"
  echo "    i2s2  (12,35,38,40)     →  [*] gpio"
  echo ""
  echo "  Then: Save pin changes → Save and reboot"
  exit 0
fi

# ── Reboot prompt ─────────────────────────────────────────────────
echo ""
echo "=== Done — reboot required for overlay to take effect ==="
echo ""
read -rp "Reboot now? [y/N] " REPLY
if [[ "$REPLY" =~ ^[Yy]$ ]]; then
  sudo reboot
else
  echo "  Run 'sudo reboot' when ready."
  echo "  After reboot, verify with:  ls /dev/spidev*"
fi
